#!/bin/zsh

bindir="/home/allen/thesis/implementation/test_processes"

if [ $OSTYPE = "linux" -o \
     $OSTYPE = "Linux" ]; then
	$bindir/disk_i386 $1
elif [ $OSTYPE = "solaris2.5" ]; then
	$bindir/disk_sparc $1
else
	echo "Unknown OSTYPE in disk" >! /tmp/ds-errs
fi
